### ISSUE TITLE
ESLint couldn't find the config "ash-nazg/sauron-node-overrides" to extend from

### ISSUE THREAD

**Issue by sscfaith** [so1ve/eslint-config#102]
```sh
npm run lint
```

> eslint . && prettier . --check

[@so1ve/eslint-config] TypeScript is not installed, fallback to JS only.

Oops! Something went wrong! :(

ESLint: 8.48.0

ESLint couldn't find the config "ash-nazg/sauron-node-overrides" to extend from. Please check that the name of the config is correct.

The config "ash-nazg/sauron-node-overrides" was referenced from the config file in "/xxx/node_modules/@es-joy/jsdoccomment/.eslintrc.cjs".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

**Comment by so1ve** [comment]
Huh? IMO this error is not related to this repository, what is `ash-nazg/sauron-node-overrides`?
