### ISSUE TITLE
HTML config is missing (?)

### ISSUE THREAD

**Issue by auvred** [so1ve/eslint-config#148]
Hi! The plugin is registered under `html` name: https://github.com/so1ve/eslint-prettier-config/blob/d7bb9b9fd260a61662d8d34be3098727d1eb7536/packages/eslint-config/src/configs/html.ts#L8

But the recommended config is destructured without renaming (under the `@html-eslint` name): 
https://github.com/so1ve/eslint-prettier-config/blob/d7bb9b9fd260a61662d8d34be3098727d1eb7536/packages/eslint-config/src/configs/html.ts#L21

Also I noticed that it isn't used in the factory (maybe it was a mistake)
https://github.com/so1ve/eslint-prettier-config/blob/d7bb9b9fd260a61662d8d34be3098727d1eb7536/packages/eslint-config/src/factory.ts#L6-L25

**Comment by so1ve** [comment]
Thanks for the reminder, I completely missed this part when migrating from classic ESLint config 😅 Fixed in https://github.com/so1ve/eslint-prettier-config/commit/fe9148fc0edba6ef40322f6a797b23f4ddfc6532
